# Generated by Django 5.1.6 on 2025-05-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_created_lots_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_lots_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='top_three_lots_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='won_lots_count',
        ),
    ]
