# Generated by Django 5.1.6 on 2025-04-20 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='lots/main/')),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='lots/additional/')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='lots/additional/')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='lots/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction_end', models.DateTimeField()),
                ('category', models.CharField(choices=[('Транспорт', 'Транспорт'), ('Картины', 'Картины'), ('Недвижимость', 'Недвижимость'), ('Украшения', 'Украшения'), ('Книги', 'Книги'), ('Электроника', 'Электроника'), ('Антиквариат', 'Антиквариат'), ('Одежда', 'Одежда'), ('Спортивные товары', 'Спортивные товары'), ('Музыкальные инструменты', 'Музыкальные инструменты'), ('Коллекционные предметы', 'Коллекционные предметы'), ('Мебель', 'Мебель')], default='Транспорт', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.lot')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
