# Generated by Django 5.1.6 on 2025-05-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lot',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/У'), ('not_specified', 'Не указано'), ('damaged', 'Повреждено'), ('refurbished', 'Восстановлено')], default='not_specified', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='lot',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='lot',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tags',
            field=models.CharField(blank=True, help_text='Введите теги через запятую (например: антиквариат, винтаж, редкий)', max_length=200, verbose_name='Теги'),
        ),
    ]
