# Generated by Django 5.1.6 on 2025-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='tags',
            field=models.CharField(blank=True, help_text='Введите теги через запятую (например: антиквариат, винтаж, редкий)', max_length=200, null=True, verbose_name='Теги'),
        ),
    ]
