# Generated by Django 5.1.6 on 2025-05-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_lot_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_auto',
        ),
        migrations.DeleteModel(
            name='AutoBid',
        ),
    ]
