# Generated by Django 5.1.6 on 2025-05-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_comment_options_lot_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
