# Generated by Django 5.1.6 on 2025-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lot',
            name='has_been_extended',
            field=models.BooleanField(default=False, help_text='Indicates if the auction has been extended due to no bids.', verbose_name='Has been extended'),
        ),
    ]
